## for NATS service configuration see #scripts/nats-bootstrap/values-nats.yaml.tmpl

image: &image_anchor
  image:
    pullPolicy: Always
    repository:
      tag: latest
      url: ghcr.io/metal-automata

env: &env_anchor
  env:
    namespace: default
    facility: sandbox
    log_level: debug
    endpoints:
      nats:
        url: nats://nats:4222
        timeout: 60s
      otel:
        authenticate: false
        url: jaeger:4317
      fleetdb:
        authenticate: false
        url: http://fleetdb:8000
        oidc_audience_url: # to be filled once oauth is available in the sandbox
        oidc_issuer_url:   # to be filled once oauth is available in the sandbox
        oidc_client_id: # to be filled by each service below (exampe: conditionorc.env.endpoints.fleetdb.client_id)
        oidc_scopes:    # to be filled by each service below (exampe: conditionorc.env.endpoints.fleetdb.client_scopes)
      conditionorc:
        authenticate: false
        url: http://conditionorc-api:9001
        oidc_audience_url: # to be filled once oauth is available in the sandbox
        oidc_issuer_url:   # to be filled once oauth is available in the sandbox
        oidc_client_id: # to be filled by each service below (exampe: flasher.env.endpoints.conditionorc.client_id)
        oidc_scopes:    # to be filled by each service below (exampe: flasher.env.endpoints.conditionorc.client_scopes)
      component_inventory:
        authenticate: false
        url: http://component-inventory:8020

# Credits to the Tinkerbell project for the Smee DHCP and iPXE service
# 
# https://github.com/tinkerbell/charts/blob/20cdc1260fd90710f051e436fe713cf93f7bb130/tinkerbell/stack/values.yaml#L66
#
# The DHCP and iPXE service
smee:
  <<: *env_anchor
  <<: *image_anchor
  # In this setup Smee uses the host network to serve DHCP, TFTP, IPXE
  # Follow the steps in notes/smee-dhcp-ipxe.md to have this setup correctly
  enabled: false
  public_intferface: <>
  image:
    pullPolicy: Always
    repository:
      tag: latest
      url: quay.io/tinkerbell

fleetdb:
  enable_oidc: false
  <<: *env_anchor
  <<: *image_anchor
  image: # Temporary until helm chart conversion is done
    pullPolicy: Always
    repository:
      tag: latest
      url: localhost:5001
  nats:
    publishStreamPrefix: com.hollow.sh.fleetdb.events

conditionorc:
  <<: *image_anchor
  <<: *env_anchor
  conditions_api:
    enable_server_enroll: true
    enable_inband_firmware_install: true
  orchestrator_api:
  image: # Temporary until helm chart conversion is done
    pullPolicy: Always
    repository:
      tag: latest
      url: localhost:5001
    # uncomment once oauth service is availble in sandbox
    # env:
    #   endpoints:
    #     fleetdb:
    #       client_id: conditionorc-api
    #       client_scopes: "read:server create:server:attributes update:server:attributes delete:server:attributes"

agent:
  <<: *env_anchor
  <<: *image_anchor
  image: # Temporary until helm chart conversion is done
    pullPolicy: Always
    repository:
      tag: latest
      url: localhost:5001
    # uncomment once oauth service is availble in sandbox
    # env:
    #   endpoints:
    #     fleetdb:
    #       client_id: flasher
    #       client_scopes: "read:server read:server:credentials read:server:component read:server:versioned-attributes read:server-component-firmwares read:server-component-firmware-sets"

syncer:
  enable_cronjob: false
  enable_job: false
  enable_env: false
  schedule: '"00 08 * * *"'
  <<: *env_anchor
  <<: *image_anchor
  image: # Temporary until helm chart conversion is done
    pullPolicy: Always
    repository:
      tag: latest
      url: localhost:5001
  endpoints:
    s3: &s3_endpoint_anchor
      region: us-east-1
      url: us-east-1
      bucket: bucket1
      access_key: accessKey
      secret_key: secretKet
    asrr:
      <<: *s3_endpoint_anchor
    github:
      openbmc_token: redacted
    artifacts:
      url: http://minio:9000
    firmware_manifest:
      url: http://modeldata/modeldata.json

minio:
  fullnameOverride: minio
  environment:
    MINIO_DOMAIN: minio
  resources:
    requests:
      memory: 512Mi
  replicas: 1
  persistence:
    enabled: false
  mode: standalone
  rootUser: rootuser
  rootPassword: rootpass123
  buckets:
    - name: bucket1
      policy: none
      purge: false
  svcaccts:
    - user: rootuser
      accessKey: accessKey
      secretKey: secretKey

postgresql:
  fullnameOverride: postgresql
  image:
    pullPolicy: IfNotPresent
  auth:
    postgresPassword: postgres
    username: user
    password: hunter2
    database: fleetdb
  passwordUpdateJob:
    enabled: true
  primary:
    service:
      type: NodePort
    persistence:
      volumeName: db
      size: 250Mi

chaos-mesh:
  enabled: false

#https://github.com/chaos-mesh/chaos-mesh/tree/master/helm/chaos-mesh
controllerManager:
  leaderElection:
    enabled: false
dashboard:
  securityMode: false
chaosDaemon:
  runtime: containerd
  socketPath: /run/containerd/containerd.sock
