apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-service: agent
    kind: controller
  name: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-service: agent
  template:
    metadata:
      labels:
        k8s-service: agent
    spec:
      terminationGracePeriodSeconds: 1200
      containers:
        - name: agent
          image: {{ .Values.agent.image.repository.url }}/agent:{{ .Values.agent.image.repository.tag }}
          imagePullPolicy: {{ $.Values.agent.image.pullPolicy }}
          command: [
           "agent",
           "service",
           "--outofband",
           "--store",
           "serverservice",
           "--config",
           "/etc/agent/config.yaml",
           "--enable-pprof",
           "--log-level",
           "debug",
           "--fault-injection",
           "--facility-code",
           "{{ .Values.agent.env.facility }}"
          ]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/agent
            - name: nats-creds-volume
              mountPath: /etc/nats
              readOnly: true
            - mountPath: /tmp
              name: downloads-scratch
          env:
            - name: AGENT_NATS_URL
              value: "{{ .Values.agent.env.endpoints.nats.url }}"
            - name: AGENT_NATS_CONNECT_TIMEOUT
              value: "{{ .Values.agent.env.NATS_CONNECT_TIMEOUT }}"
            - name: AGENT_NATS_KV_REPLICAS
              value: "0"
            - name: AGENT_SERVERSERVICE_ENDPOINT
              value: "{{ .Values.agent.env.endpoints.fleetdb.url }}"
            - name: AGENT_SERVERSERVICE_DISABLE_OAUTH
              value: "{{ not .Values.agent.env.endpoints.fleetdb.authenticate }}"
            - name: AGENT_SERVERSERVICE_FACILITY_CODE
              value: "{{ .Values.agent.env.facility }}"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "{{ .Values.agent.env.endpoints.otel.url }}"
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "{{ not .Values.agent.env.endpoints.otel.authenticate }}"
            - name: AGENT_SERVERSERVICE_OIDC_AUDIENCE_ENDPOINT
              value: "{{ .Values.agent.env.endpoints.fleetdb.oidc_audience_url }}"
            - name: AGENT_SERVERSERVICE_OIDC_ISSUER_ENDPOINT
              value: "{{ .Values.agent.env.endpoints.fleetdb.oidc_issuer_url }}"
            - name: AGENT_SERVERSERVICE_OIDC_CLIENT_SCOPES
              value: "{{ .Values.agent.env.endpoints.fleetdb.oidc_client_scopes }}"
            - name: AGENT_SERVERSERVICE_OIDC_CLIENT_ID
              value: "{{ .Values.agent.env.endpoints.fleetdb.oidc_client_id }}"
              #- name: AGENT_SERVERSERVICE_OIDC_CLIENT_SECRET
              #  valueFrom:
              #    secretKeyRef:
              #      name: agent-secrets
              #      key: serverservice-oidc-client-secret
            - name: AGENT_NATS_CREDS_FILE
              value: /etc/nats/nats.creds
          securityContext:
            capabilities:
              drop:
                - NET_RAW
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          resources:
            limits:
              cpu: 200m
              memory: 200M
            requests:
              cpu: 200m
              memory: 200M
          ports:
            - name: metrics-port
              containerPort: 9090
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics-port
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics-port
            initialDelaySeconds: 5
      volumes:
        - name: config-volume
          configMap:
            name: agent-config
        - name: nats-creds-volume
          secret:
            secretName: agent-secrets
            items:
              - key: agent-nats-creds
                path: nats.creds
        - name: downloads-scratch
          emptyDir: {}
      restartPolicy: Always
